name: Deploy test-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.10
        with: 
          host: ${{  secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: true
          script: |
            cd /root/resource/nginx/
            ls -al
            rm -rf test-deploy
            git clone https://github.com/liuyunhe/test-deploy.git -b ${{ github.ref_name }}
            cd test-deploy
            npm install
            npm run build

